# https://docs.astral.sh/uv/guides/integration/github/

name: Python test

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
#      - "test"
#    paths:
#      - '<path>/**'
#      - '.github/workflows/<name>-python-test.yaml'
  pull_request:
    branches:
      - "main"
#    paths:
#      - '<path>/**'
#      - '.github/workflows/<name>-python-test.yaml'

jobs:
  uv:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Enable caching
        uses: astral-sh/setup-uv@v7
        with:
#          cache-dependency-glob: "<path>/uv.lock"
          enable-cache: true

      - name: Install the project
#        working-directory: ./<path>
        run: uv sync --locked --all-extras --dev

      - name: Run tests
#        working-directory: ./<path>
        run: uv run pytest tests
